In [1]:
import pandas as pd

In [2]:
df_population_data = pd.read_csv('data.csv',encoding='shift-jis')

In [3]:
df_population_data

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0          1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1          2   青森県  大正    9.0  1920.0   756454   381293   375161
2          3   岩手県  大正    9.0  1920.0   845540   421069   424471
3          4   宮城県  大正    9.0  1920.0   961768   485309   476459
4          5   秋田県  大正    9.0  1920.0   898537   453682   444855
..       ...   ...  ..    ...     ...      ...      ...      ...
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 8 columns]

In [4]:
type(df_population_data)

pandas.core.frame.DataFrame

In [7]:
pd.set_option('display.max_rows',50)

In [8]:
df_population_data

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0          1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1          2   青森県  大正    9.0  1920.0   756454   381293   375161
2          3   岩手県  大正    9.0  1920.0   845540   421069   424471
3          4   宮城県  大正    9.0  1920.0   961768   485309   476459
4          5   秋田県  大正    9.0  1920.0   898537   453682   444855
..       ...   ...  ..    ...     ...      ...      ...      ...
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 8 columns]

In [9]:
pd.reset_option('display.max_rows')

In [10]:
df_population_data

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0          1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1          2   青森県  大正    9.0  1920.0   756454   381293   375161
2          3   岩手県  大正    9.0  1920.0   845540   421069   424471
3          4   宮城県  大正    9.0  1920.0   961768   485309   476459
4          5   秋田県  大正    9.0  1920.0   898537   453682   444855
..       ...   ...  ..    ...     ...      ...      ...      ...
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 8 columns]

In [11]:
pd.set_option('display.max_columns',5)

In [12]:
df_population_data

     都道府県コード 都道府県名  ...    人口（男）    人口（女）
0          1   北海道  ...  1244322  1114861
1          2   青森県  ...   381293   375161
2          3   岩手県  ...   421069   424471
3          4   宮城県  ...   485309   476459
4          5   秋田県  ...   453682   444855
..       ...   ...  ...      ...      ...
934       43   熊本県  ...   841046   945124
935       44   大分県  ...   551932   614406
936       45   宮崎県  ...   519242   584827
937       46  鹿児島県  ...   773061   875116
938       47   沖縄県  ...   704619   728947

[939 rows x 8 columns]

In [13]:
pd.reset_option('isplay.max_columns')

In [14]:
df_population_data

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0          1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1          2   青森県  大正    9.0  1920.0   756454   381293   375161
2          3   岩手県  大正    9.0  1920.0   845540   421069   424471
3          4   宮城県  大正    9.0  1920.0   961768   485309   476459
4          5   秋田県  大正    9.0  1920.0   898537   453682   444855
..       ...   ...  ..    ...     ...      ...      ...      ...
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

[939 rows x 8 columns]

In [21]:
df_population_data.head()

   都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0        1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1        2   青森県  大正    9.0  1920.0   756454   381293   375161
2        3   岩手県  大正    9.0  1920.0   845540   421069   424471
3        4   宮城県  大正    9.0  1920.0   961768   485309   476459
4        5   秋田県  大正    9.0  1920.0   898537   453682   444855

In [22]:
df_population_data.head(10)

   都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
0        1   北海道  大正    9.0  1920.0  2359183  1244322  1114861
1        2   青森県  大正    9.0  1920.0   756454   381293   375161
2        3   岩手県  大正    9.0  1920.0   845540   421069   424471
3        4   宮城県  大正    9.0  1920.0   961768   485309   476459
4        5   秋田県  大正    9.0  1920.0   898537   453682   444855
5        6   山形県  大正    9.0  1920.0   968925   478328   490597
6        7   福島県  大正    9.0  1920.0  1362750   673525   689225
7        8   茨城県  大正    9.0  1920.0  1350400   662128   688272
8        9   栃木県  大正    9.0  1920.0  1046479   514255   532224
9       10   群馬県  大正    9.0  1920.0  1052610   514106   538504

In [15]:
df_population_data.tail(10)

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
929       38   愛媛県  平成   27.0  2015.0  1385262   654380   730882
930       39   高知県  平成   27.0  2015.0   728276   342672   385604
931       40   福岡県  平成   27.0  2015.0  5101556  2410418  2691138
932       41   佐賀県  平成   27.0  2015.0   832832   393073   439759
933       42   長崎県  平成   27.0  2015.0  1377187   645763   731424
934       43   熊本県  平成   27.0  2015.0  1786170   841046   945124
935       44   大分県  平成   27.0  2015.0  1166338   551932   614406
936       45   宮崎県  平成   27.0  2015.0  1104069   519242   584827
937       46  鹿児島県  平成   27.0  2015.0  1648177   773061   875116
938       47   沖縄県  平成   27.0  2015.0  1433566   704619   728947

In [16]:
df_population_data.sample(10)

     都道府県コード 都道府県名  元号  和暦（年）   西暦（年）   人口（総数）    人口（男）    人口（女）
561       46  鹿児島県  昭和   50.0  1975.0  1723902   804365   919537
297       17   石川県  昭和   25.0  1950.0   957279   460859   496420
508       40   福岡県  昭和   45.0  1970.0  4027416  1932033  2095383
699       43   熊本県  平成    2.0  1990.0  1840326   869441   970885
717       14  神奈川県  平成    7.0  1995.0  8245900  4209525  4036375
288        8   茨城県  昭和   25.0  1950.0  2039418   993694  1045724
815       18   福井県  平成   17.0  2005.0   821592   397271   424321
259       25   滋賀県  昭和   20.0  1945.0   860911   394802   466109
137       44   大分県  昭和    5.0  1930.0   945771   465994   479777
901       10   群馬県  平成   27.0  2015.0  1973115   973283   999832

In [17]:
df_population_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   都道府県コード  939 non-null    int64
 1   都道府県名    939 non-null    object
 2   元号       939 non-null    object
 3   和暦（年）    939 non-null    float64
 4   西暦（年）    939 non-null    float64
 5   人口（総数）   939 non-null    int64
 6   人口（男）    939 non-null    int64
 7   人口（女）    939 non-null    int64
dtypes: float64(2), int64(4), object(2)
memory usage: 58.8+ KB

In [18]:
df_population_data.describe()

,都道府県コード,和暦（年）,西暦（年）,人口（総数）,人口（男）,人口（女）
count,939.000000,939.000000,939.000000,9.390000e+02,9.390000e+02,9.390000e+02
mean,23.975506,25.005325,1967.523962,2.104324e+06,1.033620e+06,1.070703e+06
std,13.558310,16.937643,28.852766,1.970612e+06,9.890101e+05,9.826168e+05
min,1.000000,2.000000,1920.000000,4.546750e+05,2.228020e+05,2.318730e+05
25%,12.000000,11.000000,1942.500000,1.000186e+06,4.846355e+05,5.160885e+05
50%,24.000000,22.000000,1970.000000,1.461197e+06,7.026970e+05,7.583210e+05
75%,36.000000,37.500000,1992.500000,2.144998e+06,1.044104e+06,1.097804e+06
max,47.000000,60.000000,2015.000000,1.351527e+07,6.666690e+06,6.848581e+06

In [19]:
df_population_data.describe().round(0)

       都道府県コード  和暦（年）   西暦（年）      人口（総数）      人口（男）      人口（女）
count    939.0  939.0   939.0       939.0      939.0      939.0
mean      24.0   25.0  1968.0   2104324.0  1033620.0  1070703.0
std       14.0   17.0    29.0   1970612.0   989010.0   982617.0
min        1.0    2.0  1920.0    454675.0   222802.0   231873.0
25%       12.0   11.0  1942.0   1000186.0   484636.0   516088.0
50%       24.0   22.0  1970.0   1461197.0   702697.0   758321.0
75%       36.0   38.0  1992.0   2144998.0  1044104.0  1097804.0
max       47.0   60.0  2015.0  13515271.0  6666690.0  6848581.0

In [20]:
df_population_data.groupby(by='都道府県名')[['人口（総数）','人口（男）','人口（女）']].mean().round(0)

          人口（総数）      人口（男）      人口（女）
都道府県名
三重県    1534021.0   743367.0   790655.0
京都府    2135318.0  1044094.0  1091224.0
佐賀県     830574.0   395551.0   435024.0
兵庫県    4233525.0  2067583.0  2165942.0
北海道    4606104.0  2272235.0  2333869.0
千葉県    3591668.0  1789947.0  1801721.0
和歌山県    978371.0   471086.0   507286.0
埼玉県    4040109.0  2023428.0  2016681.0
大分県    1142165.0   544738.0   597427.0
大阪府    6380772.0  3167759.0  3213014.0
奈良県     993523.0   479186.0   514337.0
宮城県    1801086.0   884667.0   916418.0
宮崎県    1024880.0   492893.0   531986.0
富山県     993676.0   479457.0   514219.0
山口県    1433457.0   692875.0   740582.0
山形県    1208076.0   583306.0   624770.0
山梨県     775774.0   378483.0   397291.0
岐阜県    1698390.0   828214.0   870177.0
岡山県    1679700.0   810947.0   868753.0
岩手県    1279266.0   620465.0   658802.0
島根県     783345.0   378945.0   404400.0
広島県    2347026.0  1146442.0  1200584.0
徳島県     793727.0   382320.0   411407.0
愛媛県    1385961.0   664193.0   721768.0
愛知県    4938295.0  2457583.0  2480712.0
新潟県    2300825.0  1115898.0  1184927.0
東京都    9357393.0  4740644.0  4616749.0
栃木県    1610964.0   791048.0   819915.0
沖縄県     983287.0   477057.0   506230.0
滋賀県     992977.0   483653.0   509325.0
熊本県    1679704.0   800656.0   879047.0
石川県     995672.0   479601.0   516072.0
神奈川県   5072212.0  2582037.0  2490175.0
福井県     743214.0   359213.0   384001.0
福岡県    3927586.0  1903328.0  2024259.0
福島県    1904837.0   926054.0   978783.0
秋田県    1163377.0   562366.0   601010.0
群馬県    1651464.0   807647.0   843817.0
茨城県    2249191.0  1110756.0  1138435.0
長崎県    1477374.0   715120.0   762254.0
長野県    1984244.0   959837.0  1024408.0
青森県    1275593.0   616330.0   659263.0
静岡県    2892099.0  1422674.0  1469426.0
香川県     905636.0   437365.0   468271.0
高知県     785564.0   376501.0   409063.0
鳥取県     566553.0   271488.0   295065.0
鹿児島県   1718576.0   813283.0   905294.0